#!/usr/bin/env python3

import os

# Print the HTTP headers
print("Content-Type: text/html")
print()  # Blank line to separate headers from the body

# Generate the HTML content
print("<html>")
print("<head><title>CGI Example</title></head>")
print("<body>")
print("<h1>Hello from CGI!</h1>")
print("<p>This is a dynamic response generated by a Python CGI script.</p>")

# Print environment variables (optional)
print("<h2>Environment Variables:</h2>")
print("<ul>")
for key, value in os.environ.items():
    print(f"<li>{key}: {value}</li>")
print("</ul>")

print("</body>")
print("</html>")